# 목차

---

<br>

# Exception

메소드가 실패함을 호출자에게 알리는 방법

1.  반환값(return)을 통해 알리는 방법

    전통적 방법

    - 단점

      ❗ 반환값과 연산값의 구분이 모호함

      ❗ 오류에 대한 자세한 정보를 알려줄 수 없음.

      ❗ 사용자가 함수 실패를 반드시 처리하도록 강제할 수 없다.

      ❗ 정상적인 흐름의 코드와 오류를 처리하는 코드가 분리되지 않음.

<br>

2.  Out 파라미터를 사용하는 방법

    1번 방법에서 반환값과 연산결과를 나누자.

    C# 에서 Try로 시작하는 메서드가 이 방법을 사용

    - 장점

      💡 함수의 성공 실패 여부와 반환값을 분리

      💡 오류에 대한 세부적인 정보 전달

    - 단점

      ❗ 사용자가 실패를 반드시 처리하게 강제 할 수 없다.

      ❗ 정상적인 흐름의 코르와 오류를 처리하는 코드가 분리되지 않는다.

      ❗ 함수 사용법이 까다롭다.

<br>

3.  예외를 사용하는 방법

    1.  메서드가 실패할 경우 (장점)

        `throw`키워드를 사용해서 예외를 던진다.

        오류의 전달과 메서드의 반환값이 완전히 분리 된다.

        Exception 클래스의 다양한 속성과 메서드 등을 이용해서 오류에 대한 다양한 정보를 전달 가능.

    2.  메서드에서 예외가 발생할 경우

        예외를 처리하지 않을 경우 프로그램이 종료된다

            => 오류 처리의 강제성이 생김

        try - Catch문을 통해 오류를 처리한다.

        ```C#
        try
        {
            FileManager.CopyFile("C://a.txt", "D://b.txt");
        }
        catch ( Exception e )
        {
            Console.WriteLine(e.Message);
        }
        ```

    💡 예외 처리특징

    1. 오류 처리에 대한 강제성이 생긴다.

    2. 정상적인 흐름의 코드와 오류 처리를 위한 코드를 분리 할 수 있다.

<br>

📍 Exception 권장 사항

| 반환값 사용               | 예외 사용   |
| ------------------------- | ----------- |
| 중요하지 않은 사소한 오류 | 중요한 오류 |

<br>

# 예외 처리 방법

1.  예외가 일어나는 구간에 대해 각각 처리 하는 방법

    ```C#
    try
    {
        WebClient wc = new WebClient();
        string s = wc.DownloadString("http://www.naver.com");
        Console.WriteLine(s);
    }
    //각각의 예외 처리
    catch (System.ArgumentException e) { }
    catch (System.Net.WebException e) { }
    catch (System.NotSupportedException e) { }
    ```

2.  모든 예외를 같이 처리하는 방법

    ```C#
    try
    {
        WebClient wc = new WebClient();
        string s = wc.DownloadString("http://www.naver.com");
        Console.WriteLine(s);
    }
    //한번에 처리
    catch (System.Eception e) { }
    ```

3.  특정 예외만 처리하고 나머지 일괄 처리

    ```C#
    try
    {
        WebClient wc = new WebClient();
        string s = wc.DownloadString("http://www.naver.com");
        Console.WriteLine(s);
    }
    //한번에 처리
    catch (System.ArgumentException e) { }  //특정 예외
    catch (System.Eception e) { }           //일괄 처리
    ```

    ❗ 순차적으로 진행되기 때문에 `catch (System.Eception e) { }`가 먼저 있으면 안된다.

        (`return`)과 비슷.

# System.Exception

1. 모든 예외 클래스는 `System.Exception`클래스로 부터 파생된다.

2. System.Exception의 주요 멤버

   | Message                | StackTrace                                                             |
   | ---------------------- | ---------------------------------------------------------------------- |
   | 예외를 설명하는 문자열 | 예외의 근원지부터 catch블록에 도달 할 때까지의 모든 메서드에 대한 정보 |

   ```C#
   catch (System.Exception e) {
       Console.WriteLine(e.Message);        //해당 에러의 정보를 알 수 있음
       Console.WriteLine(e.StackTrace);     //callSatck을 알려줌.
   }
   ```

# 예외 다시 전달하기.

throw를 통해 전달 할 수 있다.

```C#
static void foo()
{
    Server wc = new Server();
    try
    {
        wc.Connect();
    }
    catch(TimeoutException e)
    {
        //..
        throw e;
        throw;      //항상 좋은 표기법
    }
}
```

why `throw;` Better than `throw e;`

- `throw e;` 를 하게 될 경우 해당 콜스택이 제대로 표기가 되지 않는다.

  Foo안에서 e가 시작된 것으로 판단.

- `throw;`를 사용할 경우 이전 콜스택이 다 나온다.

# 예외 필터

catch에 들어가게 되면 성능 저하가 있다.

=> 💡 예외 필터 사용

```C#
WebClient wc = new WebClient();
try
{
    string s = wc.DownloadString("http://www.naver.com");
}
catch (WebException e)
{
    if (e.Status == WebExceptionStatus.NameResolutionFailure)
    {
        Console.WriteLine("URL이 잘못 되었습니다.");
    }
    else if (e.Status == WebExceptionStatus.Timeout)
    {
        Console.WriteLine("URL이 잘못 되었습니다.");
    }
    else
    {
        Console.WriteLine("다른 문제");
    }
}
```

catch에 들어가게 되면 성능 저하가 있다.

=> 💡 예외 필터 사용

```C#
try
{
    string s = wc.DownloadString("http://www.naver.com");
}
catch (WebException e) when (e.Status == WebExceptionStatus.NameResolutionFailure)
{
    Console.WriteLine("URL이 잘못 되었습니다.");
}
catch (WebException e) when (e.Status == WebExceptionStatus.Timeout)
{
    Console.WriteLine("URL이 잘못 되었습니다.");
}
catch (Exception e)
{
}
wc.Dispose();
```

# 예외 필터 사용 예제

## 핕터를 이용한 로깅

`when`으로 로그를 찍게 할 수 있다.

    catch문 안으로 들어가면 성능 저하가 있을 수 있다.

```C#
static void Foo()
{
    Server wc = new Server();
    try
    {
        wc.Connect();
    }
    catch (Exception e) when (Logging(e))
    {
        Console.WriteLine("Foo");
    }
}
static bool Logging(Exception e)
{
    Console.WriteLine($"Log : {e.Message}");
    return false;
}
```

## 필터를 통한 반복문 제어

```C#
static void Foo()
{
    int retryCount = 0;
    bool bSuccess = false;
    Server wc = new Server();
    while (bSuccess == false)
    {
        try
        {
            wc.Connect();
            bSuccess = true;
        }
        // catch (Exception e) when (++retryCount < 4)
        // {
        //     //if (++retryCount < 4)
        //     Console.WriteLine("One More Try");
        //     //else
        //     //    throw
        // }
        //아래와 같으나 catch를 들어가서 성능 저하가 있음
        catch (Exception e) when (++retryCount < 4)
        {
            Console.WriteLine("One More Try");
        }
    }
}
```

# Try Final

1. catch vs finally

   | catch                             | finally                  |
   | --------------------------------- | ------------------------ |
   | try블록 안에서 "예외 발생시 실행" | try 벗어날시 "항상 실행" |

❗ 예외를 던지건 return을 하건 무조건 실행됨.

    ❓ when use?)  자원 반납할때 유용함.

```C#
try
{
    throw new Exception();      // finally 실행
    return;                     // finally 실행
}
finally
{
    Console.WriteLine("finally");
}
```

## Use Finally

C# 에서 자원관리

1. new로 생성한 일반 객체들

   GC로 인해 자동으로 수집된다.

   명시적으로 자원을 해제할 필요가 없다.

2. 파일, 네트워크 등의 자원 관리하는 객체

   `Dispose()` 메소드를 호출해서 면시적으로 자원 해제

이렇게 파일에서 Exception이 일어난 경우 Dispose()가 작동이 안되므로 finally를 통해 한다.

```C#
using System;
using System.IO;

class Program
{
    static void Main()
    {
        FileStream fs = null;

        try
        {
            fs = new FileStream("a.txt", FileMode.CreateNew);
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);
        }
        finally
        {
            fs.Dispose();
        }
    }
}
```

## using을 이용한 자원 관리

자원을 해제해주며 가장 많이 사용하는 코드는 아래와 같다.

```C#
FileStream fs = new FileStream("a.txt", FileMode.CreateNew);

try
{
    //..
}
finally
{
    if (fs != null)
        fs.Dispose();
}
```

너무나 많이 사용되기 때문에 해당 내용을 함축해서 만드는 키워드(`using`) 등장.

자원관리 (Dispose)자동으로 해준다. == 
위 코드와 동일.

```C#
using (FileStream fs = new FileStream("a.txt", FileMode.CreateNew);)
{
    try
    {
        //...
    }
    catch(Exception e)
    {
        //..
    }
}
```
